### ISSUE TITLE
org.springframework.web.context.ContextLoaderListener  enhance failed

### ISSUE THREAD

**Issue by RaymondLam1** [alibaba/bytekit#23]
# Problem

We fail to use [one java agent](https://github.com/alibaba/one-java-agent) to enhance `org.springframework.web.context.ContextLoaderListener` in Spring MVC and exception stack is here：
```
java.lang.ClassFormatError: Class file version does not support constant tag 16 in class file org/springframework/web/context/ContextLoaderListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3296)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1455)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1959)
	at com.taobao.tomcat.container.context.loader.AliWebappClassLoaderBase.loadClass(AliWebappClassLoaderBase.java:114)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1833)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:536)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:518)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:148)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5138)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5745)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1016)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:992)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:639)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:2015)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:303)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createContext(MBeanFactory.java:805)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:586)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:303)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

# Analysis
Referenced from:
* https://stackoverflow.com/questions/30313255/reflections-java-8-invalid-constant-type/30320312#30320312
* https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4 

As you can see, `tag 16` is `CONSTANT_MethodType` and according to:

```
* The operand of each ldc instruction and each ldc_w instruction must be a valid index into the constant_pool table. The constant pool entry referenced by that index must be of type:
  - CONSTANT_Integer, CONSTANT_Float, or CONSTANT_String if the class file version number is less than 49.0.
  - CONSTANT_Integer, CONSTANT_Float, CONSTANT_String, or CONSTANT_Class if the class file version number is 49.0 or 50.0.
  - CONSTANT_Integer, CONSTANT_Float, CONSTANT_String, CONSTANT_Class, CONSTANT_MethodType, or CONSTANT_MethodHandle if the class file version number is 51.0.
 ```

We know that `CONSTANT_MethodType` is only supported if the bytecode version is 51 which means jdk7

Therefore, it may be that the original bytecode was compiled and generated by jdk 6, but our enhanced bytecode uses the features of jdk 7.  We need change the version of the generated bytecode to a higher one referring to https://github.com/alibaba/arthas/issues/1223

**Comment by hengyunabc** [comment]
这个是因为是增强的字节码里使用了下面的语法，导致会出现 ldc_w CONSTANT_MethodType ：

```
Runtime.getRuntime().addShutdownHook(new Thread(tracerProvider::close));
```

不要在增强代码里使用这种高版本jdk才会使用的语法。

**Comment by RaymondLam1** [comment]
We convert
```
Runtime.getRuntime().addShutdownHook(new Thread(tracerProvider::close));
```
to 
```
Runnable runnable = new Runnable() {
    @Override
    public void run() {
        tracerProvider.close();
    }
};
Runtime.getRuntime().addShutdownHook(new Thread(runnable));
```
Referenced from:
* [anonymous-classes jdk version](https://stackoverflow.com/questions/38607057/in-which-version-of-java-were-anonymous-classes-introduced)
* [anonymous-classes ](https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html)

However we got another problem:
```
Caused by: java.lang.VerifyError: Illegal type at constant pool entry 92 in class org.springframework.web.context.ContextLoaderListener
Exception Details:
  Location:
    org/springframework/web/context/ContextLoaderListener.contextInitialized(Ljavax/servlet/ServletContextEvent;)V @28: invokestatic
  Reason:
    Constant pool index 92 is invalid
  Bytecode:
    0x0000000: 1232 4db8 0038 2cb6 003e 1400 3fb2 0046
    0x0000010: b600 4ab6 004e 4eb2 0054 1256 b800 5cb8
    0x0000020: 0062 3a04 b800 672d b800 6cb6 0072 b800
    0x0000030: 7619 04b6 007a b600 7eb6 0081 3a05 b800
    0x0000040: 8619 05b6 008c b600 8f3a 06bb 0091 592a
    0x0000050: 1905 b700 943a 07b8 009a bb00 9c59 1907
    0x0000060: b700 9fb6 00a3 1906 b800 a919 0612 abb6
    0x0000070: 00af 3a08 1908 12b1 b900 b702 00b8 00bd
    0x0000080: b900 c302 00b9 00c7 0100 3a09 1909 b900
    0x0000090: cd01 003a 0a01 3a0b b200 d312 d5b6 00db
    0x00000a0: 2a2b 3a11 3a10 1910 1911 b600 03b6 0004
    0x00000b0: 57a7 0003 190a c600 5d19 0bc6 0019 190a
    0x00000c0: b900 e001 00a7 004e 3a0c 190b 190c b600
    0x00000d0: e4a7 0042 190a b900 e001 00a7 0038 3a0c
    0x00000e0: 190c 3a0b 190c bf3a 0d19 0ac6 0025 190b
    0x00000f0: c600 1919 0ab9 00e0 0100 a700 163a 0e19
    0x0000100: 0b19 0eb6 00e4 a700 0a19 0ab9 00e0 0100
    0x0000110: 190d bf19 09b9 00e7 0100 a700 0f3a 0f19
    0x0000120: 09b9 00e7 0100 190f bfb2 00d3 12e8 b600
    0x0000130: dbb1 
```
We found the new problem can also be avoid by updating [bytekit InstrumentTransformer](https://github.com/alibaba/bytekit/blob/master/bytekit-core/src/main/java/com/alibaba/bytekit/asm/instrument/InstrumentTransformer.java)

just add the following code
```
if (targetClassNode.version < Opcodes.V1_8) {
    targetClassNode.version = Opcodes.V1_8;
}
```
