### ISSUE TITLE
gtihub ci不稳定，非常奇怪

### ISSUE THREAD

**Issue by hengyunabc** [alibaba/bytekit#26]
比如：

```
[INFO] Running com.alibaba.bytekit.asm.TryCatchBlockTest
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.alibaba.bytekit.asm.TryCatchBlockTest
Error:  com.alibaba.bytekit.asm.TryCatchBlockTest.test  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalAccessError: class java.io.FileOutputStream$1 tried to access private field java.io.FileOutputStream.fd (java.io.FileOutputStream$1 and java.io.FileOutputStream are in module java.base of loader 'bootstrap')
	at java.base/java.io.FileOutputStream$1.close(FileOutputStream.java:398)
	at java.base/java.io.FileDescriptor.closeAll(FileDescriptor.java:355)
	at java.base/java.io.FileOutputStream.close(FileOutputStream.java:396)
	at com.alibaba.bytekit.utils.IOUtils.close(IOUtils.java:77)
	at com.alibaba.bytekit.utils.IOUtils.close(IOUtils.java:63)
	at com.alibaba.bytekit.utils.FileUtils.writeByteArrayToFile(FileUtils.java:87)
	at com.alibaba.bytekit.utils.FileUtils.writeByteArrayToFile(FileUtils.java:48)
	at com.alibaba.bytekit.utils.FileUtils.writeByteArrayToFile(FileUtils.java:33)
	at com.alibaba.bytekit.utils.Decompiler.decompile(Decompiler.java:38)
	at com.alibaba.bytekit.asm.TryCatchBlockTest.test(TryCatchBlockTest.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

看 jdk 里的代码：

```java
    public void close() throws IOException {
        if (closed) {
            return;
        }
        synchronized (closeLock) {
            if (closed) {
                return;
            }
            closed = true;
        }

        FileChannel fc = channel;
        if (fc != null) {
            // possible race with getChannel(), benign since
            // FileChannel.close is final and idempotent
            fc.close();
        }

        fd.closeAll(new Closeable() {
            public void close() throws IOException {
               fd.close();
           }
        });
    }
```

这个 Closeable 使用 fd 肯定是没问题的。不知道是github 有问题，还是jvm有问题。不能稳定重现。

**Comment by hengyunabc** [comment]
貌似是 EnhancerByCGLIBTest 导致的，可能它最后执行时，测试就会成功。如果它先执行了，jvm就会出问题。
